# form some test case for Transition Matrix P
TEST_CASES = [{'input': {'coord_a': [1, 2],
                         'coord_b': [0, 1],
                         'ball_pos': 1,
                         'move_a': [-1, 0],
                         'move_b': [-1, 0]},
               'expect': [{'next_coord_a': [0, 2],
                           'next_coord_b': [0, 1],
                           'next_ball_pos': 1,
                           'reward': 0,
                           'done': False}]},

              {'input': {'coord_a': [1, 2],
                         'coord_b': [0, 1],
                         'ball_pos': 1,
                         'move_a': [-1, 0],
                         'move_b': [0, 1]},
               'expect': [{'next_coord_a': [1, 2],
                           'next_coord_b': [0, 2],
                           'next_ball_pos': 1,
                           'reward': 0,
                           'done': False},
                          {'next_coord_a': [0, 2],
                           'next_coord_b': [0, 1],
                           'next_ball_pos': 0,
                           'reward': 0,
                           'done': False}]},
              {'input': {'coord_a': [0, 3],
                         'coord_b': [0, 2],
                         'ball_pos': 1,
                         'move_a': [0, 1],
                         'move_b': [0, 1]},
               'expect': [{'next_coord_a': [0, 3],
                           'next_coord_b': [0, 2],
                           'next_ball_pos': 0,
                           'reward': -100,
                           'done': True}]},
              {'input': {'coord_a': [0, 3],
                         'coord_b': [0, 2],
                         'ball_pos': 1,
                         'move_a': [1, 0],
                         'move_b': [0, 1]},
               'expect': [{'next_coord_a': [1, 3],
                           'next_coord_b': [0, 3],
                           'next_ball_pos': 1,
                           'reward': -100,
                           'done': True}]},
              {'input': {'coord_a': [1, 2],
                         'coord_b': [0, 2],
                         'ball_pos': 1,
                         'move_a': [-1, 0],
                         'move_b': [0, 0]},
               'expect': [{'next_coord_a': [1, 2],
                           'next_coord_b': [0, 2],
                           'next_ball_pos': 1,
                           'reward': 0,
                           'done': False}]},
              {'input': {'coord_a': [1, 2],
                         'coord_b': [0, 2],
                         'ball_pos': 0,
                         'move_a': [-1, 0],
                         'move_b': [0, 0]},
               'expect': [{'next_coord_a': [1, 2],
                           'next_coord_b': [0, 2],
                           'next_ball_pos': 1,
                           'reward': 0,
                           'done': False}]},

              # test if A has the ball
              {'input': {'coord_a': [1, 2],
                         'coord_b': [1, 1],
                         'ball_pos': 0,
                         'move_a': [0, -1],
                         'move_b': [0, 0]},
               'expect': [{'next_coord_a': [1, 2],
                           'next_coord_b': [1, 1],
                           'next_ball_pos': 1,
                           'reward': 0,
                           'done': False}]},
              {'input': {'coord_a': [0, 1],
                         'coord_b': [1, 0],
                         'ball_pos': 0,
                         'move_a': [0, -1],
                         'move_b': [-1, 0]},
               'expect': [{'next_coord_a': [0, 0],
                           'next_coord_b': [1, 0],
                           'next_ball_pos': 0,
                           'reward': 100,
                           'done': True},
                          {'next_coord_a': [0, 1],
                           'next_coord_b': [0, 0],
                           'next_ball_pos': 1,
                           'reward': 100,
                           'done': True}]},
              {'input': {'coord_a': [0, 1],
                         'coord_b': [0, 0],
                         'ball_pos': 0,
                         'move_a': [0, 0],
                         'move_b': [0, 0]},
               'expect': [{'next_coord_a': [0, 1],
                           'next_coord_b': [0, 0],
                           'next_ball_pos': 0,
                           'reward': 0,
                           'done': False}]},
              # test edge cases
              {'input': {'coord_a': [0, 0],
                         'coord_b': [1, 0],
                         'ball_pos': 0,
                         'move_a': [0, 0],
                         'move_b': [-1, 0]},
               'expect': [{'next_coord_a': [0, 0],
                           'next_coord_b': [1, 0],
                           'next_ball_pos': 0,
                           'reward': 100,
                           'done': True}]},
                {'input': {'coord_a': [0, 1],
                           'coord_b': [1, 1],
                           'ball_pos': 0,
                           'move_a': [0, -1],
                           'move_b': [-1,0]},
                 'expect': [{'next_coord_a': [0, 0],
                             'next_coord_b': [0, 1],
                             'next_ball_pos': 0,
                             'reward': 100,
                             'done': True}]},

              {'input': {'coord_a': [0, 2],
                         'coord_b': [0, 1],
                         'ball_pos': 1,
                         'move_a': [0, 1],
                         'move_b': [0, 1]},
               'expect': [{'next_coord_a': [0, 3],
                           'next_coord_b': [0, 2],
                           'next_ball_pos': 1,
                           'reward': 0,
                           'done': False}]}
              ]